version: '3.8'
services:
  app:
    container_name: app
    platform: linux/x86_64
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails assets:precompile && bundle exec rails s -e production"
    volumes:
      - bundle-install:/bundle
      - .:/app
      - gem-vol:/usr/local/bundle
      - node-modules:/var/www/web/node_modules
      - tmp-data:/app/tmp
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  tmp-data:
  gem-vol:
  bundle-install:
  node-modules:
